DROP PROCEDURE IF EXISTS dbo.sp_Find;
DROP PROCEDURE IF EXISTS dbo.sp_FindCode;
DROP PROCEDURE IF EXISTS dbo.sp_MatchTableName;
DROP PROCEDURE IF EXISTS dbo.sp_Join;
DROP PROCEDURE IF EXISTS dbo.sp_ScriptExecute;
DROP PROCEDURE IF EXISTS dbo.sp_ScriptInsert;
DROP PROCEDURE IF EXISTS dbo.sp_LaunchTool;